name: Stale Repo Identifier

on:
  workflow_dispatch:
  schedule:
    # Run at 4:20am UTC on the first day of every month
    - cron: '20 4 1 * *'

jobs:
  build:
    name: Generate Stale Repo Report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run stale_repos tool
      uses: docker://ghcr.io/github/stale_repos:v1
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        ORGANIZATION: ${{ secrets.ORGANIZATION }}
        # Half a year/6 months
        INACTIVE_DAYS: 180

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Stale repository report
        content-filepath: ./inputs/stale_repos.md
        assignees: 4lch4
