name: Token Expiration Checker
on:
  workflow_dispatch:
  schedule:
    # Runs at 04:20 UTC on Monday.
    - cron: '20 4 * * 1'

jobs:
  token-expiration-checker:
    name: Generate Token Expiration Report
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /users/4lch4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: JQ Script
        uses: edwardgeorge/jq-action@v1
        with:
          input: ${{ steps.get_latest_release.outputs.headers }}
          script: .["github-authentication-token-expiration"]
